# Generated by Django 2.1.7 on 2019-03-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190315_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField(verbose_name='show/aution date')),
            ],
        ),
        migrations.AlterModelOptions(
            name='servicing',
            options={'ordering': ['-date']},
        ),
    ]
